version: "3"

services:
  backend:
    container_name: nextjs-hasura-boilerplate-backend
    image: nextjs-hasura-boilerplate-backend
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    ports:
<<<<<<< HEAD
      - "8080:8080"
    restart: always
=======
      - "8081:8081"
>>>>>>> 617a151fd5db48ac16cb8f93d9aba2e02545f829

  db:
    container_name: nextjs-hasura-boilerplate-db
    image: postgres
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
